pipeline {
    agent any

    stages {
        stage('Build Docker Image') {
            steps {
                script {
                    def dockerapp = docker.build("luizfilipesm/kube-news:${env.BUILD_ID}", '-f /src/Dockerfile /src')
                    docker.withRegistry('https://registry.hub.docker.com', 'dockerhub') {
                        dockerapp.push('latest')
                        dockerapp.push("${env.BUILD_ID}")
                    }
                }
            }
        }
        stage('Deploy Kubernetes') {
            when {
                expression {
                    return env.BRANCH_NAME == 'main'
                }
            }
            environment {
                tag_version = "${env.BUILD_ID}"
            }
            steps {
                input('Deploy to Production?')
                withKubeConfig ([credentialsId: 'kubeconfig']) {
                    sh 'sed -i "s/{{TAG}}/$tag_version/g ./manifests/deployment.yml"'
                    sh 'kubectl apply -k ./manifests/'
                }
            }
        }
    }
}
